name: Sample GitHub Action

on: 
  push:
    branches:
      - main

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
      - name: mahalakshmi.chandrasekar@straive.com
        run: echo "Hello, world!"
